# Generated by Django 3.2.22 on 2023-11-01 17:09

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('cover', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='menu.meal')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='choosen_food', to='menu.meal')),
            ],
            options={
                'ordering': ['meal'],
            },
        ),
    ]
